import type { CourseLibraryEntry } from "@/types/courseLibrary";

export const COURSE_LIBRARY_SEED_DATA: CourseLibraryEntry[] = [
  {
    id: "seed-governors-cup-2026",
    courseName: "Governor's Cup 2026",
    eventName: "Governor's Cup Yacht Race",
    hostClub: "Annapolis Yacht Club",
    raceDate: "2026-07-31",
    description:
      "Annual overnight distance race from Annapolis to St. Mary's City. 68.6 NM point-to-point down the Chesapeake. Dominant leg is Thomas Point to Point No Point at 46.6 NM.",
    startLocation: "Annapolis R2 (Severn River Entrance)",
    finishLocation: "Church Point, St. Mary's City, MD",
    distanceNm: 68.6,
    raceType: "Point-to-Point Offshore",
    notes: "Warning signal 1555 EDT. Overnight race — most Cal 25s finish early Saturday morning.",
    manualStatus: "active",
    waypoints: [
      {
        id: "wp-gc-start",
        name: "Start — Annapolis R2",
        lat: 38.9417,
        lon: -76.4247,
        type: "start",
        rounding: "none",
        notes: "Severn River entrance. Staggered starts.",
      },
      {
        id: "wp-gc-tp",
        name: "WP1 — Thomas Point Shoal Light",
        lat: 38.8983,
        lon: -76.4367,
        type: "government_mark",
        rounding: "starboard",
        notes: "Leave to starboard. 2.66 NM from start on bearing 192°.",
      },
      {
        id: "wp-gc-pnp",
        name: "WP2 — Point No Point Light",
        lat: 38.13,
        lon: -76.29,
        type: "government_mark",
        rounding: "starboard",
        notes: "Leave to starboard. Dominant leg — 46.6 NM on bearing 172°.",
      },
      {
        id: "wp-gc-pl",
        name: "WP3 — Point Lookout Light",
        lat: 38.03,
        lon: -76.3283,
        type: "government_mark",
        rounding: "starboard",
        notes: "Leave to starboard. Southernmost point of race. 6.27 NM on bearing 197°.",
      },
      {
        id: "wp-gc-smj",
        name: "WP4 — St. Mary's River Junction Buoy",
        lat: 38.1417,
        lon: -76.3833,
        type: "government_mark",
        rounding: "starboard",
        notes: 'FL(2+1)R6s. Leave to starboard. 7.19 NM on bearing 339°.',
      },
      {
        id: "wp-gc-sm1",
        name: "WP5 — St. Mary's Day Marker 1",
        lat: 38.1583,
        lon: -76.3967,
        type: "mark",
        rounding: "none",
        notes: "Pass on channel side.",
      },
      {
        id: "wp-gc-sm2",
        name: "WP6 — St. Mary's Day Marker 2",
        lat: 38.17,
        lon: -76.4117,
        type: "mark",
        rounding: "none",
        notes: "Pass on channel side.",
      },
      {
        id: "wp-gc-sm3",
        name: "WP7 — St. Mary's Day Marker 3",
        lat: 38.18,
        lon: -76.4233,
        type: "mark",
        rounding: "none",
        notes: "Pass on channel side.",
      },
      {
        id: "wp-gc-finish",
        name: "Finish — Church Point Cross",
        lat: 38.1917,
        lon: -76.435,
        type: "finish",
        rounding: "none",
        notes: "Finish between committee boat and Church Point.",
      },
    ],
    results: [],
    debrief: null,
    createdAt: "2026-06-14T12:00:00.000Z",
    updatedAt: "2026-06-14T12:00:00.000Z",
  },
  {
    id: "seed-cal25-nationals-2026",
    courseName: "Cal 25 Nationals 2026",
    eventName: "Cal 25 Class National Championship",
    hostClub: "Annapolis Yacht Club",
    raceDate: "2026-09-12",
    description:
      "National championship regatta for Cal 25 one-design class. Multi-race series on windward-leeward and Olympic triangle courses.",
    startLocation: "Annapolis Race Circle",
    finishLocation: "Annapolis Race Circle",
    distanceNm: 6,
    raceType: "Buoy Racing",
    notes: "4–6 races over the weekend. One design scoring.",
    manualStatus: null,
    waypoints: [
      {
        id: "wp-nat-start",
        name: "Start / Finish",
        lat: 38.97,
        lon: -76.43,
        type: "start",
        rounding: "none",
        notes: "RC boat sets the line.",
      },
      {
        id: "wp-nat-w1",
        name: "Windward Mark",
        lat: 38.985,
        lon: -76.435,
        type: "mark",
        rounding: "port",
        notes: "RC sets position on race day.",
      },
      {
        id: "wp-nat-l1",
        name: "Leeward Mark",
        lat: 38.955,
        lon: -76.425,
        type: "mark",
        rounding: "starboard",
        notes: "RC sets position on race day.",
      },
    ],
    results: [],
    debrief: null,
    createdAt: "2026-06-14T12:00:00.000Z",
    updatedAt: "2026-06-14T12:00:00.000Z",
  },
  {
    id: "seed-ted-osius-2026",
    courseName: "Ted Osius Memorial Twilight 2026",
    eventName: "Ted Osius Memorial Twilight Regatta",
    hostClub: "Annapolis Yacht Club",
    raceDate: "2026-06-06",
    description:
      "Twilight series race in memory of Ted Osius. Short course in the Chesapeake off Annapolis. Started at 1700 EDT.",
    startLocation: "Annapolis Race Circle",
    finishLocation: "Annapolis Race Circle",
    distanceNm: 5.8,
    raceType: "Beer Can / Twilight",
    notes: "Light air, ebb tide. Tactically tricky near Thomas Point.",
    manualStatus: null,
    waypoints: [
      {
        id: "wp-to-start",
        name: "Start / Finish",
        lat: 38.9700,
        lon: -76.4300,
        type: "start",
        rounding: "none",
        notes: "",
      },
      {
        id: "wp-to-1",
        name: "Thomas Point Approach",
        lat: 38.91,
        lon: -76.435,
        type: "mark",
        rounding: "port",
        notes: "Committee-set mark.",
      },
      {
        id: "wp-to-2",
        name: "Bay Buoy",
        lat: 38.96,
        lon: -76.445,
        type: "mark",
        rounding: "starboard",
        notes: "Committee-set mark.",
      },
    ],
    results: [
      {
        id: "res-to-2026",
        finishPosition: 4,
        fleetSize: 12,
        elapsedTime: "1:23:45",
        correctedTime: "1:18:02",
        skipper: "Jay",
        crewList: "Crew A, Crew B, Crew C",
        raceNotes:
          "Bad start — port end was favored, we started middle of line. Lost two boats at the leeward mark on the first rounding.",
        weatherNotes: "SW 8–12 kts, gusts to 15. Ebb current building through the race.",
        windDirection: "SW",
        windSpeedKt: 10,
        tideCurrentNotes: "Ebb at 1.1 kt at Thomas Point SE.",
        recordedAt: "2026-06-06T22:00:00.000Z",
      },
    ],
    debrief: {
      whatWentWell: "Boat speed was solid in the puffs. Good tack execution at the top mark.",
      whatWentWrong:
        "Poor start position. Didn't recognize port end was 8° favored until too late. Lost a boat on the leeward gate by going wrong side.",
      tacticalLessons:
        "Always check the line bias in the final 5 minutes. When in doubt at the leeward gate, match the lead boats.",
      sailTrimLessons: "Traveler should have been up more in the dying moments of puffs.",
      startingLessons:
        "Get to the start line 8 minutes early. Test the line. Commit to the favored end.",
      crewNotes: "Good teamwork on mark roundings. Communication timing was off on the last drop.",
      equipmentIssues: "Cunningham line chafed — replace before next race.",
      futureImprovements:
        "Spend more time on line bias drills. Practice leeward gate decision-making.",
      updatedAt: "2026-06-07T08:00:00.000Z",
    },
    createdAt: "2026-06-06T20:00:00.000Z",
    updatedAt: "2026-06-07T08:00:00.000Z",
  },
  {
    id: "seed-wednesday-a-2026",
    courseName: "Wednesday Night Beer Can — Course A",
    eventName: "AYC Wednesday Night Beer Can Series",
    hostClub: "Annapolis Yacht Club",
    raceDate: "2026-05-28",
    description: "Weekly Wednesday night beer can race. Course A — windward/leeward.",
    startLocation: "Annapolis Race Circle",
    finishLocation: "Annapolis Race Circle",
    distanceNm: 4.5,
    raceType: "Beer Can / Buoy",
    notes: "Races start at 1800. PHRF scoring. Cal 25 in IRC A fleet.",
    manualStatus: null,
    waypoints: [
      {
        id: "wp-wa-start",
        name: "Start / Finish",
        lat: 38.9700,
        lon: -76.43,
        type: "start",
        rounding: "none",
        notes: "",
      },
      {
        id: "wp-wa-w",
        name: "Windward Mark",
        lat: 38.982,
        lon: -76.438,
        type: "mark",
        rounding: "port",
        notes: "",
      },
      {
        id: "wp-wa-l",
        name: "Leeward Mark",
        lat: 38.96,
        lon: -76.423,
        type: "mark",
        rounding: "starboard",
        notes: "",
      },
    ],
    results: [
      {
        id: "res-wa-2026",
        finishPosition: 2,
        fleetSize: 15,
        elapsedTime: "0:58:22",
        correctedTime: "0:54:10",
        skipper: "Jay",
        crewList: "Crew A, Crew B",
        raceNotes: "Great first beat. Led around the windward mark. Got caught by pressure on the run and lost the lead briefly.",
        weatherNotes: "S 12–16 kts. Gusty.",
        windDirection: "S",
        windSpeedKt: 14,
        tideCurrentNotes: "Flood at 0.8 kt.",
        recordedAt: "2026-05-28T21:30:00.000Z",
      },
    ],
    debrief: null,
    createdAt: "2026-05-28T20:00:00.000Z",
    updatedAt: "2026-05-28T21:30:00.000Z",
  },
  {
    id: "seed-wednesday-b-2026",
    courseName: "Wednesday Night Beer Can — Course B",
    eventName: "AYC Wednesday Night Beer Can Series",
    hostClub: "Annapolis Yacht Club",
    raceDate: "2026-06-04",
    description:
      "Weekly Wednesday night beer can race. Course B — triangle with offset.",
    startLocation: "Annapolis Race Circle",
    finishLocation: "Annapolis Race Circle",
    distanceNm: 5.2,
    raceType: "Beer Can / Buoy",
    notes: "Course B adds a reach leg to the triangle.",
    manualStatus: null,
    waypoints: [
      {
        id: "wp-wb-start",
        name: "Start / Finish",
        lat: 38.97,
        lon: -76.43,
        type: "start",
        rounding: "none",
        notes: "",
      },
      {
        id: "wp-wb-w",
        name: "Windward Mark",
        lat: 38.984,
        lon: -76.44,
        type: "mark",
        rounding: "port",
        notes: "",
      },
      {
        id: "wp-wb-reach",
        name: "Reach Mark",
        lat: 38.99,
        lon: -76.42,
        type: "mark",
        rounding: "starboard",
        notes: "",
      },
      {
        id: "wp-wb-l",
        name: "Leeward Mark",
        lat: 38.958,
        lon: -76.426,
        type: "mark",
        rounding: "starboard",
        notes: "",
      },
    ],
    results: [
      {
        id: "res-wb-2026",
        finishPosition: 6,
        fleetSize: 14,
        elapsedTime: "1:02:15",
        correctedTime: "0:58:44",
        skipper: "Jay",
        crewList: "Crew A, Crew B, Crew C",
        raceNotes:
          "Stuck on port tack too long on the first beat. Slow through the reach in light air — need to practice spinnaker trim in under 10 kts.",
        weatherNotes: "SSW 8–10 kts, fading at the end.",
        windDirection: "SSW",
        windSpeedKt: 9,
        tideCurrentNotes: "Slack turning ebb.",
        recordedAt: "2026-06-04T21:45:00.000Z",
      },
    ],
    debrief: null,
    createdAt: "2026-06-04T20:00:00.000Z",
    updatedAt: "2026-06-04T21:45:00.000Z",
  },
];
