// Generated by scripts/generateStrategyReferenceCatalog.mjs
// Source: Reference Data/Layline_Chapter_Reference_Extraction.json

export type ReferenceBasisKey =
  | "start_side_alignment"
  | "start_execution"
  | "upwind_core"
  | "oscillating_shift"
  | "current_and_sailing_wind"
  | "forecast_confidence"
  | "keep_options_open"
  | "tactical_observation"
  | "tactical_risk_control";

export type StrategyReferenceSource = {
  sourceFile: string;
  page: number;
  excerpt: string;
};

export type StrategyReferenceEntry = {
  summary: string;
  sources: StrategyReferenceSource[];
};

export const STRATEGY_REFERENCE_CATALOG: Record<ReferenceBasisKey, StrategyReferenceEntry> = {
  "start_side_alignment": {
    "summary": "Use first-leg strategy to choose the section of line: start right to go right, start left to go left, and use the middle when you need to preserve options.",
    "sources": [
      {
        "sourceFile": "Chapter 3 1_2.pdf",
        "page": 2,
        "excerpt": "ae i Fig, 2- Simply put, start right 10 go right, start left to go left, and start in the middle to keep your options open."
      }
    ]
  },
  "start_execution": {
    "summary": "A good start preserves clear air, acceleration room, and freedom to maneuver after the gun; near the favored end but clear of the crowd beats winning the crowd.",
    "sources": [
      {
        "sourceFile": "Chapter 3 1_2.pdf",
        "page": 4,
        "excerpt": "'A start near the favored end, but clear of congestion, is best. It provides the advantages of the favored end without risking clear air and the freedom to maneuver and accelerate, Remember—you don't need to win the start the win the race; you just need a good..."
      },
      {
        "sourceFile": "Chapter 3 2_2.pdf",
        "page": 1,
        "excerpt": "A good start is one which finds us in the front row, free and clear, not just at the gun, but a minute later, after the sprint off the line."
      }
    ]
  },
  "upwind_core": {
    "summary": "Plan upwind strategy around better wind, exploitable shifts, and favorable current, and scale commitment to how predictable those factors really are.",
    "sources": [
      {
        "sourceFile": "Chapter 7 2_2.pdf",
        "page": 1,
        "excerpt": "Strategy is Wind, Wind Shifts, and Currents 'There are three factors in planning strategy. We look for better wind. We try to take advantage of wind shifts."
      }
    ]
  },
  "oscillating_shift": {
    "summary": "In oscillating breeze, stay in phase by tacking on headers and sailing the lifted tack instead of forcing one corner too early.",
    "sources": [
      {
        "sourceFile": "Chapter 7 2_2.pdf",
        "page": 6,
        "excerpt": "As the plot shows, we continue tacking on the headers in the oscillating shifts. Gradually we find ourselves to the left of the middle of the course."
      }
    ]
  },
  "current_and_sailing_wind": {
    "summary": "Current is strategic both because it changes your path and because it changes the sailing wind, so it can break ties when the wind picture is close.",
    "sources": [
      {
        "sourceFile": "Chapter 7 2_2.pdf",
        "page": 11,
        "excerpt": "Fig, 24 — When current is not uniform, take advantage of the shift in sailing wind. In this example we have 10 knots of wind, 1 knot of current, and boats tacking through 90°."
      },
      {
        "sourceFile": "Chapter 13_Wind.pdf",
        "page": 9,
        "excerpt": "The impact depends on the direction of the current and 'our point of sail 13.4 Current and Sailing Wind Curent a strategic factor not only in its own right, but also because it changes our sailing wind."
      }
    ]
  },
  "forecast_confidence": {
    "summary": "Local observations during the hour before the race are the most critical weather input; use the forecast to frame expectations, then sail the wind you actually have.",
    "sources": [
      {
        "sourceFile": "Chapter 13_Wind.pdf",
        "page": 2,
        "excerpt": "For this reason the most critical weather information is the information we gather ourselves, during the hour before the race. Our task is to integrate the information we gather into the broader forecast, and then use it in predicting local conditions."
      },
      {
        "sourceFile": "Chapter 13_Wind.pdf",
        "page": 5,
        "excerpt": "Sail the wind, not the forecast. Fig."
      }
    ]
  },
  "keep_options_open": {
    "summary": "When the next shift or side advantage is unclear, lower commitment, keep watching for change, and preserve options instead of forcing a corner.",
    "sources": [
      {
        "sourceFile": "Chapter 7 2_2.pdf",
        "page": 1,
        "excerpt": "pursue our strategy with conviction, When we are unsure of 'what to expect, our strategy will change."
      },
      {
        "sourceFile": "Chapter 3 1_2.pdf",
        "page": 2,
        "excerpt": "ae i Fig, 2- Simply put, start right 10 go right, start left to go left, and start in the middle to keep your options open."
      }
    ]
  },
  "tactical_observation": {
    "summary": "Describe position clearly, including relation to the course and how much of each tack remains, so the whole team understands the constraint behind the next call.",
    "sources": [
      {
        "sourceFile": "Chapter 8 4_4.pdf",
        "page": 8,
        "excerpt": "One helpful description of position is the ratio of each tack remaining."
      }
    ]
  },
  "tactical_risk_control": {
    "summary": "When the picture is uncertain, lean on what you control: boat handling, boat speed, staying near the fleet, and taking only the shifts you can read.",
    "sources": [
      {
        "sourceFile": "Chapter 8 4_4.pdf",
        "page": 7,
        "excerpt": "No More Tactics 'The trick is to rely on things you can control: boat han- dling and boat speed."
      },
      {
        "sourceFile": "Chapter 8 3_4.pdf",
        "page": 3,
        "excerpt": "Second, if you don't know what to expect, then minimize leverage to minimize the impact of shifts. (Have you ever been unable to anticipate the next shift?"
      }
    ]
  }
};
